import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` p-5 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex items-center justify-between">
          <ul className="flex items-center gap-x-5">
            <li>
              <Link href={'/'}>Home</Link>
            </li>
            <li>
              <Link href={'/about'}>About</Link>
            </li>
            <li>
              <Link href={'/contact'}>Contact</Link>
            </li>
            <li>
              <Link href={'/blog'}>Blog</Link>
            </li>
            <li>
              <Link href={'/docs'}>Docs</Link>
            </li>
            <li>
              <Link href={'/sheet'}>sheet</Link>
            </li>
          </ul>

          <div className="space-x-4">
            <Link href={'/login'}>login</Link>
            <Link href={'/singup'}>singup</Link>
          </div>
        </nav>
        <br />
        <hr />
        {children}

        <footer className="text-xl text-center rounded-md font-bold bg-white/10 w-full py-5">
          <h2> Footer </h2>
        </footer>
      </body>
    </html>
  );
}
