import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` p-10 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <ul className="flex items-center gap-x-6">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/about">About</Link>
            </li>
            <li>
              <Link href="/blog">blog</Link>
            </li>
            <li>
              <Link href="/setting">setting</Link>
            </li>
            <li>
              <Link href="/user">user</Link>
            </li>
            <li>
              <Link href="/person">person</Link>
            </li>

            <li>
              <Link href="/post">Post</Link>
            </li>
          </ul>
        </header>

        <br />
        <hr />

        {children}

        <footer className="flex mt-auto">
          <h1>footer data</h1>
        </footer>
      </body>
    </html>
  );
}
